name: LockcardEssentials
version: 1.1
authors:
  - SirSpigotAPI
  - zorryno
main: de.lockcard.essentials.Main
commands:
  lockglow:
    usage: "/lockglow [Player]"
    description: "Enable/Disable glowing"
permissions:
  glow.*:
    description: "All glow permissions"
    default: op
    children:
      - glow.self
      - glow.other
  glow.self:
    description: "Enable/Disable glowing for yourself"
    default: true
  glow.other:
    description: "Enable/Disable glowing for others"
    default: op

